### ISSUE TITLE
Relay all messages through an external MTA

### ISSUE THREAD

**Issue by fciubotaru** [fciubotaru/z-pec#3]
As most PEC solutions use and externally certified provider, the mailbox server will need to the able to relay all trafic through the certified provider.

**Comment by csfercoci** [comment]
In order to send meessage from zimbra to pec server, you must configure zimbra server, but also the relay server.
The relay server(pec) must have the zimbra server domain in his trust zone
In zimbra server, in web administration interface in mta administration part,external/internal server must point to the relay server(pec).  

![inbound emails](https://f.cloud.github.com/assets/3026315/46901/33b592ae-58a3-11e2-9505-24de3cabdab0.png)
